# Projektarbeit zum Datensatz Airline Passenger Satisfaction

## Aufgaben 1

A1:
    Gruppe:
        Hasan Hüseyin Demirci,
        Andreas Hubertus,
        Sebastian Rein,
        Vitalii Solonychnyi

Datensatz:
    Airline Passenger Satisfaction
    https://www.kaggle.com/datasets/teejmahal20/airline-passenger-satisfaction/data


## Aufgaben 2

### A1:
Wissenschaftliche Publikationen:
https://d-nb.info/989290174/34

Forschungsfrage:
Bis zum 23.11.25 soll der Korrelationskoeffizient zwischen mindestens fünf Korelationsfaktorenmit Zufriedenheit gefunden werden.

### A2:


SMART-Ziele:
Specific:
Measurable:
Achievable:
Realistic:
Time-bound:

### A3:

In [8]:
import numpy as np
import time

size = 100000

big_python_list_without_Numpy = list(range(size))
big_python_array_with_Numpy = np.array(size)

start_time_big_python_list_without_Numpy = time.time()
for i in range(len(big_python_list_without_Numpy)):
    big_python_list_without_Numpy[i] = big_python_list_without_Numpy[i] **2
end_time_big_python_list_without_Numpy = time.time()

print("Time taken for big Python list without Numpy: ", end_time_big_python_list_without_Numpy - start_time_big_python_list_without_Numpy)

start_time_big_python_list_with_Numpy_end = time.time()
big_python_array_with_Numpy = big_python_array_with_Numpy **2
end_time_big_python_list_with_Numpy_end = time.time()

print("Time taken for big Python array with Numpy: ", end_time_big_python_list_with_Numpy_end - start_time_big_python_list_with_Numpy_end)

Time taken for big Python list without Numpy:  0.022841691970825195
Time taken for big Python array with Numpy:  0.0002830028533935547


Ergebnis:
Numpy ist um einiges schneller, bei size = 1000 ca 0.0007 Unterschied (nicht bemerkbar), jedoch mit zunehmender Größe size = 100000 ca 0.02 Unterschied (mit noch größeren immer weiter auseinandergehend). Numpy hat kaum veränderungen bei der Laufzeit.

### A4:
Erstellung eines 2D- Array (10x10) mit den Zahlen von 1 - 100 in aufsteigender Reihe.


In [27]:
array = np.arange(100).reshape(10,10)

a Extrahierung der ersten, fünften und letzten Zeile des Arrays

In [13]:
rows = array[[0,4,9]]
print(rows)

[[ 0  1  2  3  4  5  6  7  8  9]
 [40 41 42 43 44 45 46 47 48 49]
 [90 91 92 93 94 95 96 97 98 99]]


b Wahl der Elementer der 3. und 7. Spalte, die in ungeraden Zeilen stehen.

In [16]:
cols = array[1::2, [2,6]]
print(cols)

[[12 16]
 [32 36]
 [52 56]
 [72 76]
 [92 96]]


c 3x3 Subarray

In [17]:
subarray = array[:3,:3]
print(subarray)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]]


d Änderung jedes Elementes der 2. und 4. Zeile des Arrays, durch ersetzen seines negativen Wertes

In [29]:
array[[1,3]] = -array[[1,3]]
print(array)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


e Ersetzen aller Werte < 25 durch 0

In [26]:
array[array < 25] = 0
print(array)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


## Aufgaben 3


### A1

a laden des Datensatzes 

In [32]:
import pandas as pd

df = pd.read_csv("train.csv")

df.head()

Unnamed: 0      id  Gender      Customer Type  Age   Type of Travel  \
0           0   70172    Male     Loyal Customer   13  Personal Travel   
1           1    5047    Male  disloyal Customer   25  Business travel   
2           2  110028  Female     Loyal Customer   26  Business travel   
3           3   24026  Female     Loyal Customer   25  Business travel   
4           4  119299    Male     Loyal Customer   61  Business travel   

      Class  Flight Distance  Inflight wifi service  \
0  Eco Plus              460                      3   
1  Business              235                      3   
2  Business             1142                      2   
3  Business              562                      2   
4  Business              214                      3   

   Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                  4  ...                       5   
1                                  2  ...                       1   
2                                  2  ...                       5   
3                                  5  ...                       2   
4                                  3  ...                       3   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 4                 3                 4                4   
1                 1                 5                 3                1   
2                 4                 3                 4                4   
3                 2                 5                 3                1   
4                 3                 4                 4                3   

   Inflight service  Cleanliness  Departure Delay in Minutes  \
0                 5            5                          25   
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   
4                 3            3                           0   

   Arrival Delay in Minutes             satisfaction  
0                      18.0  neutral or dissatisfied  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  
4                       0.0                satisfied  

[5 rows x 25 columns]

b
User Datensatz hat 24 Spalten und 103904.000000 Zeilen

c Die bezeichnungen sind alle intuitiv klar

d Ausreißer können in ... entstehen

In [33]:
df.describe()

Unnamed: 0             id            Age  Flight Distance  \
count  103904.000000  103904.000000  103904.000000    103904.000000   
mean    51951.500000   64924.210502      39.379706      1189.448375   
std     29994.645522   37463.812252      15.114964       997.147281   
min         0.000000       1.000000       7.000000        31.000000   
25%     25975.750000   32533.750000      27.000000       414.000000   
50%     51951.500000   64856.500000      40.000000       843.000000   
75%     77927.250000   97368.250000      51.000000      1743.000000   
max    103903.000000  129880.000000      85.000000      4983.000000   

       Inflight wifi service  Departure/Arrival time convenient  \
count          103904.000000                      103904.000000   
mean                2.729683                           3.060296   
std                 1.327829                           1.525075   
min                 0.000000                           0.000000   
25%                 2.000000                           2.000000   
50%                 3.000000                           3.000000   
75%                 4.000000                           4.000000   
max                 5.000000                           5.000000   

       Ease of Online booking  Gate location  Food and drink  Online boarding  \
count           103904.000000  103904.000000   103904.000000    103904.000000   
mean                 2.756901       2.976883        3.202129         3.250375   
std                  1.398929       1.277621        1.329533         1.349509   
min                  0.000000       0.000000        0.000000         0.000000   
25%                  2.000000       2.000000        2.000000         2.000000   
50%                  3.000000       3.000000        3.000000         3.000000   
75%                  4.000000       4.000000        4.000000         4.000000   
max                  5.000000       5.000000        5.000000         5.000000   

        Seat comfort  Inflight entertainment  On-board service  \
count  103904.000000           103904.000000     103904.000000   
mean        3.439396                3.358158          3.382363   
std         1.319088                1.332991          1.288354   
min         0.000000                0.000000          0.000000   
25%         2.000000                2.000000          2.000000   
50%         4.000000                4.000000          4.000000   
75%         5.000000                4.000000          4.000000   
max         5.000000                5.000000          5.000000   

       Leg room service  Baggage handling  Checkin service  Inflight service  \
count     103904.000000     103904.000000    103904.000000     103904.000000   
mean           3.351055          3.631833         3.304290          3.640428   
std            1.315605          1.180903         1.265396          1.175663   
min            0.000000          1.000000         0.000000          0.000000   
25%            2.000000          3.000000         3.000000          3.000000   
50%            4.000000          4.000000         3.000000          4.000000   
75%            4.000000          5.000000         4.000000          5.000000   
max            5.000000          5.000000         5.000000          5.000000   

         Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  
count  103904.000000               103904.000000             103594.000000  
mean        3.286351                   14.815618                 15.178678  
std         1.312273                   38.230901                 38.698682  
min         0.000000                    0.000000                  0.000000  
25%         2.000000                    0.000000                  0.000000  
50%         3.000000                    0.000000                  0.000000  
75%         4.000000                   12.000000                 13.000000  
max         5.000000                 1592.000000               1584.000000

### A2:

Indizierung und Manipulation:
durchschnittliche Zufriedenheit nach gender, customer type oder type of travel.
einflussvon Flugverspätungen auf Zufriedenheit
Bewertung von Servicekategorien
Zufriedenheit nach alter
Korrelation zwischen Flight Distance und Zufriedenheit


Hypothesen:
1. Älteren Leuten (>70 Jahre) schätzen die Möglichkeit der Onlinebuchung mehr wert, bemängeln jedoch die Suaberkeit mehr.

